import jsPDF from 'jspdf';

/**
 * Export email content as a .txt file
 */
export const exportAsTxt = ({ subject, emailBody, linkedinDM, followUpEmail, prompt }) => {
    const divider = '─'.repeat(50);
    const content = [
        '═'.repeat(50),
        '  MailGen AI — Generated Email',
        '═'.repeat(50),
        '',
        `Date: ${new Date().toLocaleString()}`,
        '',
        divider,
        '  PROMPT',
        divider,
        prompt || 'N/A',
        '',
        divider,
        '  SUBJECT LINE',
        divider,
        subject || 'N/A',
        '',
        divider,
        '  COLD EMAIL',
        divider,
        emailBody || 'N/A',
        '',
        divider,
        '  LINKEDIN DM',
        divider,
        linkedinDM || 'N/A',
        '',
        divider,
        '  FOLLOW-UP EMAIL',
        divider,
        followUpEmail || 'N/A',
        '',
        '═'.repeat(50),
        '  Generated by MailGen AI',
        '═'.repeat(50),
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mailgen-${slugify(subject)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};

/**
 * Export email content as a styled PDF
 */
export const exportAsPdf = ({ subject, emailBody, linkedinDM, followUpEmail, prompt }) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    let y = 20;

    const addPageIfNeeded = (requiredSpace = 30) => {
        if (y + requiredSpace > doc.internal.pageSize.getHeight() - 20) {
            doc.addPage();
            y = 20;
        }
    };

    // Header
    doc.setFillColor(37, 99, 235); // primary-600
    doc.rect(0, 0, pageWidth, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('MailGen AI', margin, 26);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, pageWidth - margin, 26, { align: 'right' });

    y = 55;

    // Prompt section
    doc.setTextColor(100, 116, 139); // gray-500
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text('PROMPT', margin, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105); // gray-600
    doc.setFontSize(10);
    const promptLines = doc.splitTextToSize(prompt || 'N/A', contentWidth);
    doc.text(promptLines, margin, y);
    y += promptLines.length * 5 + 10;

    // Sections
    const sections = [
        { label: 'SUBJECT LINE', content: subject },
        { label: 'COLD EMAIL', content: emailBody },
        { label: 'LINKEDIN DM', content: linkedinDM },
        { label: 'FOLLOW-UP EMAIL', content: followUpEmail },
    ];

    sections.forEach((section) => {
        if (!section.content) return;
        addPageIfNeeded(40);

        // Section divider
        doc.setDrawColor(226, 232, 240); // gray-200
        doc.setLineWidth(0.3);
        doc.line(margin, y, pageWidth - margin, y);
        y += 10;

        // Section label
        doc.setTextColor(37, 99, 235); // primary-600
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text(section.label, margin, y);
        y += 8;

        // Section content
        doc.setTextColor(30, 41, 59); // gray-800
        doc.setFontSize(10.5);
        doc.setFont('helvetica', 'normal');
        const lines = doc.splitTextToSize(section.content, contentWidth);
        lines.forEach((line) => {
            addPageIfNeeded(8);
            doc.text(line, margin, y);
            y += 5.5;
        });
        y += 8;
    });

    // Footer
    addPageIfNeeded(20);
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;
    doc.setTextColor(148, 163, 184); // gray-400
    doc.setFontSize(8);
    doc.text('Generated by MailGen AI', margin, y);

    doc.save(`mailgen-${slugify(subject)}.pdf`);
};

function slugify(text) {
    if (!text) return 'email';
    return text
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '')
        .slice(0, 40);
}
